### ISSUE TITLE
relax bindgen version requirement

### ISSUE THREAD

**Issue by houqp** [ccouzens/leptonica-sys#1]
Is there any reason you want to pin bindgen to the exact version? As a library crate, it's better to relax the requirement so it is less likely to cause conflicts to downstream libraries.

**Comment by ccouzens** [comment]
Hi @houqp 

Sorry, I don't know why I didn't see this before.

I've got it that way, because it's the way the bindgen guide recommends
https://rust-lang.github.io/rust-bindgen/tutorial-1.html

If it's causing problems, I can change it. Do you know which crate it's conflicting with?

**Comment by houqp** [comment]
Setting a wildcard version would have the same effect as using latest version right? I haven't encountered any conflict with other libraries yet, but I can see things start to break when a new version of buildgen is released.
