### ISSUE TITLE
Can't compile. `stdatomic.h` not found in Window 10

### ISSUE THREAD

**Issue by Multirious** [ccouzens/leptonica-sys#16]
I'm not sure what went wrong with the installation process.
I did exactly what `tesseract-sys`/`leptonica-sys` told me to do. I also installed `leptonica:x64-windows-static-md` because one of the build errors is about missing that installation.
Before actually being able to install with `vcpkg`: I also got an error trying to `vcpkg integrate install`; from searching and screwing around, I seem to kinda fix it by adding more components to Visual Studio.

Error:
```
   Compiling leptonica-sys v0.4.4
error: failed to run custom build command for `leptonica-sys v0.4.4`

Caused by:
  process didn't exit successfully: `C:\Users\Windows10\Projects\Rust\cargo_target\debug\build\leptonica-sys-b0ac22be7bbc120f\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LEPTONICA_INCLUDE_PATH
  cargo:rerun-if-env-changed=LEPTONICA_LINK_PATHS
  cargo:rerun-if-env-changed=LEPTONICA_LINK_LIBS
  cargo:rustc-link-search=native=C:\Users\Windows10\Desktop\vcpkg\installed\x64-windows-static-md\lib
  cargo:rustc-link-lib=leptonica-1.83.1
  cargo:rustc-link-lib=zlib
  cargo:rustc-link-lib=tiff
  cargo:rustc-link-lib=lzma
  cargo:rustc-link-lib=jpeg
  cargo:rustc-link-lib=turbojpeg
  cargo:rustc-link-lib=openjp2
  cargo:rustc-link-lib=libwebpdecoder
  cargo:rustc-link-lib=libwebpdemux
  cargo:rustc-link-lib=libwebpmux
  cargo:rustc-link-lib=libwebp
  cargo:rustc-link-lib=libsharpyuv
  cargo:rustc-link-lib=libpng16
  cargo:rustc-link-lib=gif

  --- stderr
  C:\Users\Windows10\Desktop\vcpkg\installed\x64-windows-static-md\include\leptonica/environ.h:69:10: fatal error: 'stdatomic.h' file not found
  thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("C:\\Users\\Windows10\\Desktop\\vcpkg\\installed\\x64-windows-static-md\\include\\leptonica/environ.h:69:10: fatal error: 'stdatomic.h' file not found\n")', C:\Users\Windows10\.cargo\registry\src\github.com-1ecc6299db9ec823\leptonica-sys-0.4.4\build.rs:87:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ccouzens** [comment]
Thank you for your patience.

I've added an issue to request for someone who can help with Windows issues (such as this one). https://github.com/ccouzens/leptonica-sys/issues/17

**Comment by thlstsul** [comment]
should add stdatomic.h head file path to INCLUDE environment variable

**Comment by Multirious** [comment]
> should add stdatomic.h head file path to INCLUDE environment variable

Where should I get that file?

**Comment by thlstsul** [comment]
in the clang install path, like "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\lib\clang\12.0.0\include"

**Comment by thlstsul** [comment]
> in the clang install path, like "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\lib\clang\12.0.0\include"

**Comment by thlstsul** [comment]
> 

in the clang install path, like "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\lib\clang\12.0.0\include"

**Comment by ccouzens** [comment]
Can you try again with [0.4.7](https://crates.io/crates/leptonica-sys/0.4.7) please?

https://github.com/ccouzens/leptonica-sys/pull/23 has been released to address this issue.
