### ISSUE TITLE
work with multiple include paths (e.g. the cmake installed pkgconfig file)

### ISSUE THREAD

**Issue by bavardage** [ccouzens/leptonica-sys#19]
In https://github.com/DanBloomberg/leptonica/blob/master/lept.pc.cmake#L12 both include paths are listed

```
Cflags: -I${includedir} -I${includedir}/leptonica
```

In https://github.com/ccouzens/leptonica-sys/blob/main/build.rs#L63-L65 we're popping off the trailing directory from the first include path, which then results in a bad include path

A potential fix could be to only pop if the last path component is 'leptonica' - curious for thoughts

**Comment by ccouzens** [comment]
Something like this? https://github.com/ccouzens/leptonica-sys/pull/20

**Comment by bavardage** [comment]
That would solve my exact issue, yeah

**Comment by ccouzens** [comment]
Published as 0.4.6
https://crates.io/crates/leptonica-sys/0.4.6
