### ISSUE TITLE
different soname native library

### ISSUE THREAD

**Issue by ava57r** [ccouzens/leptonica-sys#8]
Hello.

leptonica has different name in platform and name depends on build system(autotools, cmake)

https://github.com/DanBloomberg/leptonica/issues/253

Could You support this option?

**Comment by ccouzens** [comment]
Sure, it may take me a week or two to get time to try and fix this as I'm a little busy at the moment.

Do you know of a platform this is currently broken on? It will be useful to confirm I've fixed it.

**Comment by ava57r** [comment]
cmake building does not work for leptonica

https://github.com/DanBloomberg/leptonica/issues/253#issuecomment-323389510

https://github.com/DanBloomberg/leptonica/issues/253#issuecomment-323404012

**Comment by ava57r** [comment]
I will to use `make` with name `lept`, so it works without fixes.

**Comment by ccouzens** [comment]
Thank you for the PR.

I've released it as version 0.4.0

https://crates.io/crates/leptonica-sys/0.4.0
